PythonProject/ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from appTwo import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/',admin.site.urls),
    url(r'^appTwo/',include('appTwo.urls',namespace="appTwo")),
]

PythonProject/ProTwo/appTwo/urls.py
from django.conf.urls import url, include
from appTwo import views

app_name = "appTwo"

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results$',views.results,name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote$',views.vote,name='vote'),
    url(r'^login/$', views.login, name='login'),
    url(r'^about/$', views.about, name='about'),
    url(r'^placements/$', views.placements, name='placements'),
    url(r'^admissions/$', views.admissions, name='admissions'),
]

PythonProject/ProTwo/appTwo/models.py
from django.db import models

# Create your models here.
class Branch(models.Model):
    branch = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.branch

class AdmissionStats(models.Model):
    branch_name = models.ForeignKey(Branch, on_delete=models.CASCADE)
    totalIntake = models.IntegerField()
    cutoff = models.IntegerField()
    placementStats = models.IntegerField()

    def __str__(self):
        return str(self.branch_name)

class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default = 0)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text



PythonProject/ProTwo/appTwo/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from appTwo.models import Branch,AdmissionStats, Question, Choice

# Create your views here.
def index(request):
    latest_questions = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_questions':latest_questions}
    return render(request, 'appTwo/index.html',context)

def detail(request, question_id):
    question = Question.objects.get(pk = question_id)
    return render(request, 'appTwo/detail.html', {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'appTwo/detail.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except:
        return render(request, 'appTwo/detail.html', {'question':question, 'error_message':"Please select a choice"})
    else:
        selected_choice.votes+=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('appTwo:results', args=(question.id,)))


def login(request):
    return render(request, 'appTwo/login.html')

def about(request):
    return render(request, 'appTwo/about.html')

def admissions(request):
    data_list = AdmissionStats.objects.order_by('branch_name')
    data_dict = {'records': data_list}
    return render(request, 'appTwo/admissions.html', context=data_dict)

def placements(request):
    return render(request, 'appTwo/placements.html')

PythonProject/ProTwo/templates/appTwo/about.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
    <legend style="color: #636363"><h1>About Us</h1></legend>
        <br>
        <img style="align-self: center" src="{% static 'images/images.jpeg' %}">
        <br>
        <br><br>
<h4 style="text-align: justify-all">Established in 1958, Imperial College of Engineering was the first to be set up with foreign assistance. The funds from UNESCO came as Roubles from the then Soviet Union. Since then, ICE has grown from strength to strength to emerge as one of the top technical universities in the world.<br>

The institute is recognised worldwide as a leader in the field of engineering education and research. Reputed for the outstanding calibre of students programmes, the institute attracts the best students from the country for its engineering programmes. Research and academic programmes at ICE are driven by an outstanding faculty, many of whom are reputed for their research contributions internationally.<br>

ICE also builds links with peer universities and institutes, both at the national and the international levels, to enhance research and enrich its educational programmes. The alumni have distinguished themselves through their achievements in and contributions to industry, academics, research, business, government and social domains. The institute continues to work closely with the alumni to enhance its activities through interactions in academic and research programmes as well as to mobilise financial support.<br>

Over the years, the institute has created a niche for its innovative short-term courses through continuing education and distance education programmes. Members of the faculty of the institute have won many prestigious awards and recognitions, including the Shanti Swaroop Bhatnagar and Padma awards.<br>

Located in Powai, one of the northern suburbs of Mumbai, the residents of the institute reap the advantage of being in the busy financial capital of India, while at the same time enjoying the serenity of a campus known for its natural beauty. A fully residential institute, all its students are accommodated in its 15 hostels with in-house dining; the campus also provides excellent amenities for sports and other recreational facilities.<br></h4>

    </div>
    <br>
    <br>
    <br><br>
    <br>
    <br>

{% endblock %}

PythonProject/ProTwo/templates/appTwo/admissions.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <link rel="stylesheet" href="{% static 'css/icons.css' %}"/>
    <br><br><br>
    <br>
    <br>
    <br>
    <br>


<div class="container">
<h3>Admission Details for Current Academic Year are as follows : </h3>
<br>
{% if records %}
    <table>
    <thead>
    <th style="border: 5px solid white;
  width:100%;
  height:50px;
  padding: 15px;
  background-color: #2c2f35;
  color: white;
  font-size: large;">Branch</th>
    <th style="border: 5px solid white;
  width:100%;
  height:50px;
  padding: 15px;
  background-color: #2c2f35;
  color: white;
  font-size: large;">Total Intake</th>
    <th style="border: 5px solid white;
  width:100%;
  height:50px;
  padding: 15px;
  background-color: #2c2f35;
  color: white;
  font-size: large;">Cutoff</th>
    <th style="border: 5px solid white;
  width:100%;
  height:50px;
  padding: 15px;
  background-color: #2c2f35;
  color: white;
  font-size: large;">Placement(%)</th>
    </thead>
    {% for rec in records %}
        <tr>
        <td style="border: 5px solid white;
  color: #3d4451;
  font-size: medium;">{{ rec.branch_name }}</td>
        <td style="border: 5px solid white;
  color: #3d4451;
  font-size: medium;">{{ rec.totalIntake }}</td>
        <td style="border: 5px solid white;
  color: #3d4451;
  font-size: medium;">{{ rec.cutoff }}</td>
        <td style="border: 5px solid white;
  color: #3d4451;
  font-size: medium;">{{ rec.placementStats }}</td>
        </tr>
    {% endfor %}
    </table>
    <br>
    <small>Placement Statics are reported in accordance with former Academic Year</small>
{% else %}
    <h1><strong>Admission Details Will Be Displayed Shortly</strong>></h1>
{% endif %}
</div>
{% endblock %}

PythonProject/ProTwo/templates/appTwo/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/socialicon.css" %}">
    <script src="{% static "js/project.js" %}" charset="utf-8"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "css/icons.css" %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Forum" rel="stylesheet">
    <script src="{% static "js/1.js" %}"></script>
    <!-- Bootstrap -->
    <script src="{% static "js/3.js" %}"></script>
    <!-- FastClick -->
    <script src="{% static "js/2.js" %}"></script>
    <!-- NProgress -->
    <script src="{% static "js/4.js" %}"></script>
    <!-- Chart.js -->
    <script src="{% static "js/5.js" %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static "js/6.js" %}"></script>

    <title>base</title>
</head>
<body>

 <div>
       <nav class="navbar navbar-dark bg-dark navbar fixed-top">

           <div class="navbar-header"><img src="{% static "images/LOGOOO.jpg" %}" height=100 width=100 class="navbar-brand" >
             <h1 class="navbar-brand" id="coll">IMPERIAL INSTITUTE OF ENGINEERING<br></h1>

           </div>

          <div class="container" id="links">
          <p>   </p>
              <a href="{% url 'index' %}"><button type="button"  class="btn btn-space btn-outline-success">HOME</button></a>
              <a href="{%url 'appTwo:about'%}"><button type="button" class="btn btn-space btn-outline-success">ABOUT</button></a>
              <a href="{%url 'appTwo:admissions'%}"><button type="button" class="btn btn-space btn-outline-success">ADMISSIONS</button></a>
              <a href="{%url 'appTwo:login'%}"><button type="button" class="btn btn-space btn-outline-success">LOGIN</button></a>
                  <a href="{%url 'appTwo:placements'%}"><button type="button" class="btn btn-space btn-outline-success">PLACEMENTS</button></a>

   </div>
   </nav></div>

 <br><br>



        {% block body_block %}

        {% endblock %}
 <br><br><br><br>
    <div class="navbar" id="social">
    <a href="http://www.facebook.com" target="_blank"><img src="{% static "images/facebook.png" %}"></a>
<a href="http://www.twitter.com" target="_blank"><img src="{% static "images/twitter.png" %}"></a>
<a href="http://www.instagram.com" target="_blank"><img src="{% static "images/insta.png" %}"></a>
<a href="http://www.youtube.com" target="_blank"><img src="{% static "images/youtube.png" %}"></a>

  <a href="#">News</a>
  <a href="#">Contact Us</a>
    </div>
</body>
</html>

PythonProject/ProTwo/templates/appTwo/detail.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <h4>{{ question.question_text }}</h4>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'appTwo:vote' question.id %}" method="POST">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    <input type="submit" value="vote"/>
    </form>


    </div>
{% endblock %}

PythonProject/ProTwo/templates/appTwo/index.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <br>
    <br>
    <br>
    <br>

    <object align="middle">
        <video class="vid" height=500 width=1350 margin-top=1000 muted autoplay>
          <source src="{% static "images/Video.mp4" %}" type="video/mp4">
          <!--<source src="video.ogg" type="video/ogg">-->
        </video>
      </object>
     <br>
    <br>
    <br>
    <div class="container">
        <h1 style="font-family: 'Baskerville Old Face'; color: maroon">Find your Path. Pursue Your Career.</h1>
        <h4  style="color: #333333">Imperial students are doing interesting things and going interesting places with opportunities <br>they couldn't imagine possible elsewhere. Be it Computer Science, Information Technology, Production Engineering or Electronics Engineering... <br>We ensure students all-round development with our excellent technical as well as ,<br>non-technical programmes that help students map their ideal career.</h4>
        <h3><strong>So what are you waiting for?
        Join us at Imperial now!</strong></h3>
    </div>
    <br><br><br>



{% endblock %}

PythonProject/ProTwo/templates/appTwo/login.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <br><br><br> <br> <br> <br>
    <div class="container"> <a href="{% url 'admin:index' %}">Click here to  Login as Administrator</a></div>
    <br><br><br> <br> <br> <br>
{% endblock %}

PythonProject/ProTwo/templates/appTwo/placements.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <br><br><br><br><br><br>



     <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3><small></small></h3>
              </div>


            </div>



              <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Bar graph <small> Placements</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                  <!--        <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>-->
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  <!--mybarChart-->
                    <canvas id="mybarChart"></canvas>
                  </div>
                </div>
              </div>
            </div>
     </div>

        <script>
        Chart.defaults.global.legend = {
        enabled: false
      };
        // Bar chart
      var ctx = document.getElementById("mybarChart");
      var mybarChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels:  ["2012","2013", "2014", "2015", "2016", "2017"],
          datasets: [{
            label: 'COMPUTER',
            backgroundColor: "#24af91",
            data: [50,60,80,100,85,0]
          }, {
            label: 'IT',
            backgroundColor: "#d6d148",
            data: [40,50,70,90,70,95]
          },{
            label: 'ELECTRONICS',
            backgroundColor: "#bf3d3d",
            data:  [30,40,60,75,60,60]
          }, {
            label: 'PRODUCTION',
            backgroundColor: "#337ef7",
            data:  [10,15,20,30,20,30]


          }]
        },

        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: true
              }
            }]
          }
        }
      });

        </script>

 {% endblock %}

PythonProject/ProTwo/templates/appTwo/results.html
<!DOCTYPE html>
{% extends "appTwo/base.html" %}
{% load staticfiles %}
{% block body_block %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h4>{{ question.question_text }}</h4>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'appTwo:detail' question.id %}">Vote Again</a>
{% endblock %}